AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Create a load balancer that initially makes a config hc available for pinging through the 
  load balancer, and to which additional services can be added.
Parameters:

  LoadBalancerName:
    Type: String
    
  CertificateArn:
    Type: String

  VpcId:
    Type: String

  AppServerSecurityGroupID:
    Type: String
  PublicSubnet1:
    Type: String
  PublicSubnet2:
    Type: String

Resources:

  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB Allowed Ports
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0

  InboundRule:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
        IpProtocol: tcp
        FromPort: '0'
        ToPort: '65535'
        SourceSecurityGroupId: !GetAtt AlbSecurityGroup.GroupId
        GroupId: !Ref AppServerSecurityGroupID

  ECSALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref LoadBalancerName
      Scheme: internet-facing
      LoadBalancerAttributes:
      - Key: idle_timeout.timeout_seconds
        Value: '30'
      Subnets:
      - !Ref PublicSubnet1
      - !Ref PublicSubnet2
      SecurityGroups: [!Ref 'AlbSecurityGroup']

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn: ECSALB
    Properties:
      Certificates:
      - CertificateArn: !Ref CertificateArn
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref DefaultTargetGroup
      LoadBalancerArn: !Ref ECSALB
      Port: '443'
      Protocol: HTTPS

# A tip of the hat to the ECS ref arch from awslabs for the following tidbit
# We define a default target group here, as this is a mandatory Parameters
# when creating an Application Load Balancer Listener. This is not used, instead
# a target group is created per-service in each service template (../services/*)
  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: default
      VpcId: !Ref VpcId
      Port: 443
      Protocol: HTTPS


Outputs:
  ALBListenerArn:
    Description: Listener associated with the ALB
    Value: !Ref 'ALBListener'

  ALBDnsName:
    Description: DNSName associated with the ALB
    Value: !GetAtt ECSALB.DNSName
    

  HostedZoneId:
    Description: Hosted zone id associated with the ELB
    Value: !GetAtt ECSALB.CanonicalHostedZoneID
