AWSTemplateFormatVersion: '2010-09-09'
Description: >
  AWS CloudFormation template to create a new VPC
  or use an existing VPC for ECS deployment
  in Create Cluster Wizard

Resources:

  service1TaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: Service1Task
      ContainerDefinitions:
        -
          Name: service1
          Image: xtracdev/service1
          PortMappings:
            -
              ContainerPort: 4000
              HostPort: 0
          Memory: 300
  service2TaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: Service2Task
      ContainerDefinitions:
        -
          Name: service2
          Image: xtracdev/service2
          PortMappings:
            -
              ContainerPort: 4000
              HostPort: 0
          Memory: 300